version: '3.9'

services:
  web:
    container_name: 'web'
    build: './client'
    volumes:
      - './client:/app:rw'
      - './client/node_modules:/app/node_modules:rw'
    environment:
      REACT_APP_BE_SERVER_HOST: 'localhost'
      REACT_APP_BE_SERVER_PORT: '5000'
    links:
      - 'server'
    ports:
      - '3000:3000'
  
  server:
    container_name: 'server'
    build: '.'
    volumes:
      - '.:/app:rw'
      - './node_modules:/app/node_modules:rw'
    environment:
      CLARIFAI_API: ''
      POSTGRES_URI: 'postgresql://postgres:root@db:5432/smart-brain'
      REDIS_HOST: 'redis'
    links:
      - 'db'
      - 'redis'
    ports:
      - '5000:5000'

  db:
    image: 'postgres:14-alpine'
    volumes:
      - './db:/docker-entrypoint-initdb.d/:rw'
      - './db:/var/lib/db:rw'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'smart-brain'
      POSTGRES_HOST: 'db'
    ports: 
      - '5432:5432'

  redis:
    image: 'redis:6.2-alpine'